### ISSUE TITLE
Propose renaming service instance to match demo 

### ISSUE THREAD

**Issue by jschabowsky** [SolaceLabs/solace-messaging-cf-dev#12]
Right now we instruct the user to:
cf create-service solace-messaging shared test_shared_instance

but in the demo, the manifest.yml file is looking for: solace-messaging-demo-instance

Propose we change to:
cf create-service solace-messaging solace-messaging-demo-instance 

That will be more consistent and the user can jump immediately into using the PCF Dev Env.

**Comment by mdspielman** [comment]
That makes sense to me.

**Comment by PhilippeKhalife** [comment]
This is done, see latest commit.

**Comment by mdspielman** [comment]
Agreed. Closing.
