### ISSUE TITLE
CF Dev guide - indicate which VMs to run in when listing commands

### ISSUE THREAD

**Issue by solacedbaik** [SolaceLabs/solace-messaging-cf-dev#17]
It would be nice to group commands by which VM they should be run under, or perhaps show a prompt in each command indicating which environment.  It could get confusing when re-running commands and the VM to run it in isn't explicitly noted.  Perhaps have command prompts with names of the VM, and list them out with descriptions at the top of the guide.

**Comment by PhilippeKhalife** [comment]
As per the instructions:

"Login to cli-tools VM
All deployment steps require you to be logged in to the cli-tools VM"

I will consider your suggestion and add a reminder per command...
