### ISSUE TITLE
CF Dev guide - show output for running commands

### ISSUE THREAD

**Issue by solacedbaik** [SolaceLabs/solace-messaging-cf-dev#18]
Sample output for commands could be useful – if there’s a lot of output then a snippet showing what users should look for when a command completes successfully could be useful.  This doesn't have to be done for every command or for simple ones, but where a task is more involved or takes a long time, it would be useful to see what to expect.

**Comment by PhilippeKhalife** [comment]
Thanks for your feedback, I think it would be hard to capture output samples (some are very long as you noted) and to even maintain that per release in the guide.... I think adding a test at the end of major steps to show success or failure would be clearer and more maintainable. I will add something to help with that.
