### ISSUE TITLE
Error when running ./installServiceBroker.sh

### ISSUE THREAD

**Issue by peteblin** [SolaceLabs/solace-messaging-cf-dev#19]
Error processing app files: No app files found in '/Users/peteblin/Tech/Solace-Pivotal/solace-messaging-cf-dev/workspace/releases/solace-messaging.jar'
Peters-MacBook-Pro:workspace peteblin$ 

How do I fix this error?

**Comment by PhilippeKhalife** [comment]
For starters, it does not look like you are using the cli-tools VM given the folder path you have shown.

Also it seems that the solace-messaging.jar (The service broker's jar) is missing, did you do the extract from the tile as required?

**Comment by PhilippeKhalife** [comment]
This is not longer a relevant issue, the service broker installation is now using a bosh errand.

**Comment by PhilippeKhalife** [comment]
The reported issue was due to running the command from the wrong environment.
This command has been removed in newer versions of this project. Installing the service broker is done using bosh errands.
