### ISSUE TITLE
extract_tile.sh is not in the workspace directory

### ISSUE THREAD

**Issue by peteblin** [SolaceLabs/solace-messaging-cf-dev#20]
Why cd to the workspace directory where the scripts are not available?   I needed to get out of the ssh session and copy extract_tile.sh to the workspace directory.

///Output

Use extract_tile.sh to extract the relevant contents we need.

cd workspace
extract_tile.sh -t solace-messaging-1.0.0.pivotal

**Comment by PhilippeKhalife** [comment]
The project's bin scripts folder should be in the $PATH, this is automatically done if the setup is correct, are you using the setup as recommended? with the cli-tools VM?

**Comment by PhilippeKhalife** [comment]
This issue was due to running the command from the wrong environment, the commands should be run in cli-tools VM as indicated in the documentation.
