### ISSUE TITLE
Need to firm up vagrant version requirement

### ISSUE THREAD

**Issue by jschabowsky** [SolaceLabs/solace-messaging-cf-dev#7]
Due to a bug in Vagrant 1.8.5, the bosh VM was unable to complete due to ssl key login issues. An upgrade to latest version (1.9.3) made it work. Propose we change Language: 

Directly on your computer, you need to:

Install latest Git
Install latest Virtual Box
Install latest Vagrant
Shell access, use your preferred shell.

TO:

Directly on your computer, you must have or get:

Install latest Git (version 2.7.1+)
Install latest Virtual Box (version 5.1.18+)
Install latest Vagrant (version 1.9.1+)
Shell access, use your preferred shell.

That way we have captured a minimal version baseline that has been tested. Feel free to adjust Git and Virtual Box versions as those are what I have on my machine.

**Comment by mdspielman** [comment]
Good suggestion.
