### ISSUE TITLE
Wording update to Using Deployment Section

### ISSUE THREAD

**Issue by jschabowsky** [SolaceLabs/solace-messaging-cf-dev#8]
Currently, there is a block of commands to run which include creating the service and the deleting the service:
**cf delete-service -f test_shared_instance
cf services**

Following that is this sentence:
**Ideally you will bind the service you created to an application and use it. You can go ahead download and test the Solace Sample Apps, or create some of your own.**

I think maybe the delete-service stuff could be moved to the "Other useful commands and tools" section so that you are not deleting the service., then trying to use it.

**Comment by mdspielman** [comment]
Good suggestion.
